# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oZ4XkvVQWsrJJlMF8UtYXnC7iFdOikDB
"""

#1 Expressions-> * - / +
# values-> 'hello',-87.8, 6

#2.
Fruit="Apple"
#A Variable is a store of information, and a String is a type of information you would store in a Variable. Here Fruit is the variable name holding the value apple in it

#3.
a=10
print(type(a))# a is holding integer value .Integers are zero, positive or negative whole numbers without a fractional part and having unlimited precision
b=23.34
print(type(b))#b is holding float value. Float are decimal numbers having whole number part and fractional part.
c="Ineuron"
print(type(c))# c is holding string value. String is sequence of characters.

#4.
#An expression is a combination of operators and operands that is interpreted to produce some other value.And produces some value or result
x=45+ 4.5
print(x)

#5.
spam=10 # is a statement A statement is used for creating variables or for displaying values.
spam=spam+8# is a expression here spam is holding the value 10 so 10  is added to 8 gives 18 as result

#6.
bacon=22
bacon+1
print(bacon)

#7. What should the values of the following two terms be?
'spam'+'spamspam'

'spam'*3

#8. Why is eggs a valid variable name while 100 is invalid?
# A variable name should not start with numbers

#9. What three functions can be used to get the integer, floating-point number, or string version of a value?
int(),float(),str()

#10. Why does this expression cause an error? How can you fix it?
'I have eaten' +"99"+ 'burritos' # 99 is an int . int and str concatenation is not possible so by converting 99 to string it can be sorted