# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sjYKdqIU4kT3jrvfckL5NM9IA1w3nFCJ
"""



"""1.Variable naming **error**"""

45number=89

-number1=78

"""Name **error**"""

Fruit="Apple"
fruit="Apple"
print(FRUIT)

"""2."""

a=int(input("Enter first number"))
b=int(input("Enter the second number"))
print(f"Sum is {a+b}")
print(f"Difference is {a-b}")
print(f"Product is {a*b}")
c=int(input("Enter the number to find the square:"))
print(f"Square is :{c*c}")

"""3. 33 keywords
If we use keywords it throws error
"""

print=67
print(print)

"""4."""

firstname=input("Enter the firstname:")
lastname=input("Enter the last name:")
print(f"{lastname}.{firstname}@gmailcom")

"""5."""

name="Rowan"
address="34/1220"
earn="10$"
print(f"""My name is {name}
My address is {address}
I earn {earn} daily""")

"""6."""

name="Rowan"
address="56/6790"
dob="21/10/2017"
print(f"{name}.gmail.com")

"""7."""

a=22.4
print(type(a))
int(a)

b=22
print(type(b))
complex(b)