# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4x7XOBmLSjW7B56KNLRpYKwZC_0s31v
"""

'''2. In a list of values stored in a variable called spam, how would you assign the value &#39;hello&#39; as the
third value? (Assume [2, 4, 6, 8, 10] are in spam.)
Let&#39;s pretend the spam includes the list [&#39;a&#39;, &#39;b&#39;, &#39;c&#39;, &#39;d&#39;] for the next three queries.'''

"""1. What exactly is []?
list
"""

spam=[2,4,6,8,10]
spam.insert(3,'hello')
print(spam)

"""3. What is the value of spam[int(int(&#39;3&#39; * 2) / 11)]?"""

spam[int(int('3' * 2) / 11)]

"""4. What is the value of spam[-1]?"""

spam[-1]

"""5.What is the value of spam[:2]? Let's pretend bacon has the list [3.14, 'cat,' 11, 'cat,' True] for the next three questions."""

bacon=[3.14,'cat',11,'cat',True]
bacon[:2]

"""6. What is the value of bacon.index(&#39;cat&#39;)?"""

bacon.index('cat')

"""7. How does bacon.append(99) change the look of the list value in bacon?"""

bacon.append(99)
print(bacon)

"""8. How does bacon.remove(&#39;cat&#39;) change the look of the list in bacon?"""

bacon.remove('cat')
print(bacon)

"""9.What are the list concatenation and list replication operators?
+,*

10. What is difference between the list methods append() and insert()?
 append() adds an item to the end of a list, whereas . insert() inserts and item in a specified position in the list.

11. What are the two methods for removing items from a list?
pop() , and remove() methods. I

12. Describe how list values and string values are identical.
Both strings and lists have lengths: a string's length is the number of characters in the string; a list's length is the number of items in the list. Each character in a string as well as each item in a list has a position, also called an index.

List and Tuple in Python are the classes of Python Data Structures. The list is dynamic, whereas the tuple has static characteristics. This means that lists can be modified whereas tuples cannot be modified, the tuple is faster than the list because of static in nature.

14. How do you type a tuple value that only contains the integer 42?
s=(42)

15. How do you get a list value&#39;s tuple form? How do you get a tuple value&#39;s list form?
"""

An iterable can be passed as an input to the tuple () function, which will convert it to a tuple object. If you want to convert a Python list to a tuple, you can use the tuple() function to pass the full list as an argument, and it will return the tuple data type as an output.

"""16. Variables that &quot;contain&quot; list values are not necessarily lists themselves. Instead, what do they
contain?

ariables that "contain" list values don't actually contain lists directly. What do they contain instead? They contain references to list values.

17. How do you distinguish between copy.copy() and copy.deepcopy()?
"""

copy (shallow copy) doesn't create a copy of nested objects, instead it just copies the references to the nested objects, while deepcopy (deep copy) copies all the nested objects recursively. a, b, c, d, a1, b1, c1 and d1 are references to objects in memory, which are uniquely identified by their ids.

