# -*- coding: utf-8 -*-
"""Assignment02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVitLZX1HAZVdsjYPBsfpAx9I_2QEcCH

1.What are the two values of the Boolean data type? How do you write them?

The boolean data type is either True or False. In Python, boolean variables are defined by the True and False keywords.
"""

a=True
type(a)

b=False
type(b)

"""2. What are the three different types of Boolean operators?**bold text**

AND,OR,NOT
"""



"""3. Make a list of each Boolean operator&#39;s truth tables (i.e. every possible combination of Boolean
values for the operator and what it evaluate ).

True and True is True
True and False is False
False and True is False
False and False is False
True or True is True
True or False is True
False or True is True
not True is False
not False is True
AND
A B Output
1 1 1
1 0 0
0 1 0
0 0 0
OR
A B Output
1 0 1
0 1 1
1 1 1
0 0 0
NOT
A Output
1 0
0 1
"""



"""4. What are the values of the following expressions?
(5 &gt; 4) and (3 == 5)
not (5 &gt; 4)
(5 &gt; 4) or (3 == 5)
not ((5 &gt; 4) or (3 == 5))
(True and True) and (True == False)
(not False) or (not True)
"""

(5 >4) and (3 == 5)

not (5 > 4)

(5>4) or (3==5)

not ((5>4) or (3==5))

(True and True) and (True == False)

(not False) or (not True)

"""5. What are the six comparison operators?

< , <= ,>,>=,== !=

6. How do you tell the difference between the equal to and assignment operators?Describe a
condition and when you would use one.

= is used for assigning values to a variable while == is used to comapre two values
"""

a=10 # assigning values
b=20 # assigning values
if a == b : #comparison
  print(f"{a} and {b} are equal")
else:
  print(f"{a} and {b} are not equal")

"""7. Identify the three blocks in this code:
spam = 0
if spam == 10:
print(&#39;eggs&#39;)
if spam &gt; 5:
print(&#39;bacon&#39;)
else:
print(&#39;ham&#39;)
print(&#39;spam&#39;)
print(&#39;spam&#39;)
"""

spam = 0
if spam == 10:
  print('eggs')
if spam > 5:
  print('bacon')
else:
  print('ham')
  print('spam')
  print('spam')

"""8. Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, and prints
Greetings! if anything else is stored in spam.
"""

spam = int(input("Enter either 1 or 2 :"))
if spam == 1:
  print("Hello")
elif spam == 2:
  print("Howdy")
else:
  print("Greetings")

"""9.If your programme is stuck in an endless loop, what keys you’ll press?

ctrl + c

10. How can you tell the difference between break and continue?

Break statement will end up in the innermost loop if it is used within a nested loop. While using the continue statement the loops do not terminate but continuously go on with the next iteration.

11. In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?
"""

for i in range(10):
  print(i)

for i in range(0,10):
  print(i)

for i in range(0,10,1):
  print(i)

"""The range(10) call ranges from 0 up to (but not including) 10, range(0, 10) tells the loop to start at 0, and range(0, 10, 1) tells the loop to increase the variable by 1 on each iteration.

12. Write a short program that prints the numbers 1 to 10 using a for loop. Then write an equivalent
program that prints the numbers 1 to 10 using a while loop.
"""

for i in range(1,11):
  print(i)

i=1
while i<= 10:
  print(i)
  i=i+1

"""13. If you had a function named bacon() inside a module named spam, how would you call it after
importing spam?

spam.bacon()
"""