# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F02arD-pLsP4u7TvQASQ0GxG7ELgP9O0

1. Why are functions advantageous to have in your programs?
They make the code shorter, cleaner, modular, and organized.

2. When does the code in a function run: when it&#39;s specified or when it&#39;s called?

When it is called

3. What statement creates a function?

def followed by function name

4. What is the difference between a function and a function call?

Funtion is used to perform a certain set of operations . These set of operations will execute only if function call is been done .

5. How many global scopes are there in a Python program? How many local scopes?

6. What happens to variables in a local scope when the function call returns?
When the execution of the function terminates (returns), the local variables are destroyed.

7. What is the concept of a return value? Is it possible to have a return value in an expression?
A value-returning function should include a return statement, containing an expression. If an expression is not given on a return statement in a function declared with a non- void return type, the compiler issues a warning message.

8. If a function does not have a return statement, what is the return value of a call to that function?
If the function doesn't have any return statement, then it returns None

9. How do you make a function variable refer to the global variable?
Normally, when you create a variable inside a function, that variable is local, and can only be used inside that function. To create a global variable inside a function, you can use the global keyword.

10. What is the data type of None?
The None keyword is used to define a null value, or no value at all.

11. What does the sentence import areallyourpetsnamederic do?
imports a module named areallyourpetsnamederic.

12. If you had a bacon() feature in a spam module, what would you call it after importing spam?
This function can be called with spam. bacon().

13. What can you do to save a programme from crashing if it encounters an error?
When it encounters an error, the control is passed to the except block, skipping the code in between. As seen in the above code, we have moved our code inside a try and except statement. Try running the program and it should throw an error message instead of crashing the program.

14. What is the purpose of the try clause? What is the purpose of the except clause?


When it encounters an error, the control is passed to the except block, skipping the code in between. As seen in the above code, we have moved our code inside a try and except statement. Try running the program and it should throw an error message instead of crashing the program.
"""